# Generated by Django 3.2.20 on 2023-08-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=220)),
                ('city', models.CharField(max_length=220)),
                ('state', models.CharField(max_length=220)),
                ('address', models.CharField(max_length=256)),
                ('postal_address', models.CharField(max_length=256)),
                ('strip_secret_key', models.CharField(max_length=120)),
                ('strip_public_key', models.CharField(max_length=120)),
                ('dwolla_stagging', models.BooleanField(default=True)),
                ('dwolla_secret_key', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120, null=True)),
                ('logo', models.ImageField(upload_to='Logo/', verbose_name='Logo')),
                ('card_logo', models.ImageField(upload_to='Card_logo/', verbose_name='Card_Logo')),
                ('heading_1', models.CharField(max_length=120)),
                ('heading_2', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('ck_stagging', models.BooleanField(default=True)),
                ('ck_username', models.CharField(max_length=120)),
                ('ck_pass', models.CharField(max_length=120)),
                ('ck_tpaCode', models.CharField(max_length=120)),
                ('motor_stagging', models.BooleanField(default=True)),
                ('motor_public_key', models.CharField(max_length=120)),
                ('motor_private_key', models.CharField(max_length=120)),
                ('wis_inspection_stagging', models.BooleanField(default=True)),
                ('wis_username', models.CharField(max_length=120)),
                ('wis_pass', models.CharField(max_length=120)),
                ('dwolla_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=120)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('permission', models.ManyToManyField(to='accounts.CompanyPermission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('company_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.companyrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
