# Generated by Django 3.2.20 on 2023-08-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='companypermission',
            name='code',
            field=models.IntegerField(),
        ),
    ]
