# Generated by Django 3.2.20 on 2023-08-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230810_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dwolla_public_key',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
