# Generated by Django 3.2.20 on 2023-08-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230824_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepresentativePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='member_of',
            field=models.CharField(choices=[('admin', 'Admin'), ('dealer', 'Dealer'), ('repair_facility', 'Repair Facility'), ('sales_representative', 'Sales Representative'), ('agency', 'Agency')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SalesRepresentativeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('permission', models.ManyToManyField(to='accounts.SalesRepresentativePermission')),
            ],
        ),
    ]
