# Generated by Django 3.2.20 on 2023-08-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230824_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='SalesRepresentative_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.salesrepresentativerole'),
        ),
    ]
