# Generated by Django 3.2.20 on 2023-08-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_dealer_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer_of',
            field=models.CharField(choices=[('admin', 'Admin'), ('agency', 'Agency')], default=[('admin', 'Admin'), ('agency', 'Agency')], max_length=50),
        ),
        migrations.AddField(
            model_name='dealer',
            name='producer_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
